# ไฟล์นี้มีหน้าที่ สร้าง FTP Server ด้วย Docker เพื่อใช้เป็นระบบเก็บไฟล์ถาวรให้โปรเจกต์ 
# สร้าง FTP Server อัตโนมัติ 
# ตั้งชื่อผู้ใช้และรหัสผ่านได้ 
# รองรับการเชื่อมต่อแบบ Passive
# เก็บไฟล์ถาวร ไม่หายเมื่อปิดหรือรีสตาร์ต Docker
# ใช้งานร่วมกับเว็บแอปพลิเคชันได้

version: "3.8"
services:

# *---* บรรทัดนี้คือการตั้งชื่อ service ว่า ftp , Docker จะใช้ชื่อนี้เป็นตัวอ้างอิงในการสร้างและจัดการระบบ *---*
  ftp:
    image: stilliard/pure-ftpd # *---* กำหนดให้ Docker ใช้ image pure-ftpd เพื่อสร้าง FTP Server *---*
    container_name: ftp-server # *---* ตั้งชื่อ container ให้จำง่าย ใช้เรียกด้วย docker exec / docker logs ได้ *---*
   
# *---* ส่วนนี้เป็นการเปิดพอร์ตให้เครื่องภายนอกเชื่อมต่อได้ พอร์ต 21 ใช้สำหรับการเชื่อมต่อ FTP หลัก ช่วงพอร์ต 30000–30009 
# ใช้สำหรับการเชื่อมต่อแบบ Passive ซึ่งจำเป็นต่อการรับส่งไฟล์ ถ้าไม่เปิดพอร์ตช่วงนี้ การอัปโหลดหรือดาวน์โหลดอาจใช้งานไม่ได้ *---*
    ports:
      - "21:21" # Docker จะเปิดช่องทางให้ ระบบเว็บ และผู้ใช้ สามารถติดต่อกับเซิร์ฟเวอร์เก็บไฟล์ได้ ถ้าไม่เปิดพอร์ต เว็บจะ “มองไม่เห็น” ระบบเก็บไฟล์เลย
      - "30000-30009:30000-30009" # เปิดช่วงพอร์ต 30000–30009 ใช้สำหรับ Passive Mode

# กลุ่มที่ 7: การตั้งค่าผู้ใช้และระบบผ่าน environment
# *---* ส่วนนี้คือหัวใจของการตั้งค่า FTP Server ใช้กำหนดค่าต่าง ๆ โดยไม่ต้องแก้โค้ดภายใน Image *---*

    environment:
      PUBLICHOST: "127.0.0.1" # ทันทีที่ Docker สร้างระบบเสร็จ จะมีผู้ใช้ถูกสร้างอัตโนมัติ (FileZilla Client)
      FTP_USER_NAME: YJ
      FTP_USER_PASS: 1234
      FTP_USER_HOME: /home/ftpusers/ftpuser1 # กำหนดโฟลเดอร์หลักของผู้ใช้ เมื่อเข้าสู่ระบบ จะเข้ามาอยู่ในโฟลเดอร์นี้ทันที ช่วยจำกัดสิทธิ์การเข้าถึงไฟล์

# กำหนดช่วงพอร์ตสำหรับ Passive บังคับใช้ IP เดียวกันเสมอ ช่วยให้การรับส่งไฟล์เสถียร
      ADDED_FLAGS: "--passiveportrange 30000:30009 --forcepassiveip 127.0.0.1"

# *---* เชื่อมโฟลเดอร์ในเครื่องกับใน container เพื่อให้ไฟล์ไม่หายเมื่อปิด Docker *---*
    volumes:
# ไฟล์ไม่ได้อยู่แค่ใน Docker แต่ถูกเก็บไว้ในเครื่องจริงด้วย 
# ผลลัพธ์คือ ไม่ว่าจะปิดหรือรีสตาร์ต Docker ไฟล์ก็ยังอยู่ เว็บยังเห็นไฟล์ชุดเดิมเสมอ
      # ส่วนนี้คือการเชื่อมโฟลเดอร์ในเครื่องจริง กับโฟลเดอร์ภายใน container
      - ./server_files:/home/ftpusers
      # map โฟลเดอร์ server_files บนเครื่อง host ไปยัง /home/ftpusers ภายใน container
      # เพื่อให้ไฟล์ FTP ไม่หายเมื่อรีเซ็ต

    restart: always # ถ้าเซิร์ฟเวอร์เก็บไฟล์หยุดทำงาน Docker จะเปิดให้ใหม่อัตโนมัติ




# ผู้ใช้สั่งงานผ่านเว็บ เว็บส่งคำสั่งไปยังระบบที่ Docker สร้างไว้ แล้ว Docker จัดการไฟล์ให้
# Docker ทำหน้าที่สร้างและดูแลระบบเก็บไฟล์ เมื่อรัน Docker ระบบจะพร้อมใช้งานทันที เว็บจะเชื่อมต่อไปจัดการไฟล์ในระบบนั้น 
# โดยไฟล์จะถูกเก็บถาวรในเครื่องจริง แม้จะปิดหรือรีสตาร์ต Docker ข้อมูลก็ไม่หาย
# การแยกระบบเว็บกับระบบเก็บไฟล์ ช่วยให้ดูแลง่าย ปลอดภัย และขยายระบบได้ในอนาคต