# ไฟล์นี้มีหน้าที่ สร้าง FTP Server ด้วย Docker เพื่อใช้เป็นระบบเก็บไฟล์ถาวรให้โปรเจกต์ 
# สร้าง FTP Server อัตโนมัติ 
# ตั้งชื่อผู้ใช้และรหัสผ่านได้ 
# รองรับการเชื่อมต่อแบบ Passive
# เก็บไฟล์ถาวร ไม่หายเมื่อปิดหรือรีสตาร์ต Docker
# ใช้งานร่วมกับเว็บแอปพลิเคชันได้

# กลุ่มที่ 1: การกำหนดเวอร์ชันของ Docker Compose
# *---* การกำหนดเวอร์ชันของ Docker Compose ที่ใช้ในโปรเจกต์ *---*

version: "3.8"


# กลุ่มที่ 2: การประกาศ services 
# *---* การกำหนด service ที่ Docker จะสร้างขึ้น *---*

services:

# กลุ่มที่ 3: การกำหนด service FTP
# *---* บรรทัดนี้คือการตั้งชื่อ service ว่า ftp ,Docker จะใช้ชื่อนี้เป็นตัวอ้างอิงในการสร้างและจัดการระบบ *---*

  ftp:

# กลุ่มที่ 4: การเลือก Image สำหรับ FTP Server
# *---* ตรงนี้คือการกำหนดให้ Docker ใช้ image pure-ftpd เพื่อสร้าง FTP Server *---*

    image: stilliard/pure-ftpd

# กลุ่มที่ 5: การตั้งชื่อ Container
 # *---* ตั้งชื่อ container ให้จำง่าย ใช้เรียกด้วย docker exec / docker logs ได้ *---*

    container_name: ftp-server
   
# กลุ่มที่ 6: การเปิดพอร์ตสำหรับ FTP
# *---* ส่วนนี้เป็นการเปิดพอร์ตให้เครื่องภายนอกเชื่อมต่อได้ พอร์ต 21 ใช้สำหรับการเชื่อมต่อ FTP หลัก ช่วงพอร์ต 30000–30009 
# ใช้สำหรับการเชื่อมต่อแบบ Passive ซึ่งจำเป็นต่อการรับส่งไฟล์ ถ้าไม่เปิดพอร์ตช่วงนี้ การอัปโหลดหรือดาวน์โหลดอาจใช้งานไม่ได้ *---*

    ports:
      - "21:21"
      - "30000-30009:30000-30009"

# กลุ่มที่ 7: การตั้งค่าผู้ใช้และระบบผ่าน environment
# *---* ส่วนนี้คือหัวใจของการตั้งค่า FTP Server ใช้กำหนดค่าต่าง ๆ โดยไม่ต้องแก้โค้ดภายใน Image *---*

    environment:

# กำหนดที่อยู่ของเซิร์ฟเวอร์
# บอก FTP Server ว่า จะให้ผู้ใช้เชื่อมต่อผ่าน IP อะไร ในกรณีนี้ใช้เครื่องเดียวกัน

      PUBLICHOST: "127.0.0.1"
      
      FTP_USER_NAME: YJ
      # กำหนดชื่อผู้ใช้ FTP

      FTP_USER_PASS: 1234
      # กำหนดรหัสผ่านของผู้ใช้ FTP

      FTP_USER_HOME: /home/ftpusers/ftpuser1
      # กำหนดโฟลเดอร์หลักของผู้ใช้
      # เมื่อเข้าสู่ระบบ จะเข้ามาอยู่ในโฟลเดอร์นี้ทันที ช่วยจำกัดสิทธิ์การเข้าถึงไฟล์

# ตั้งค่าการเชื่อมต่อแบบ Passive
# ส่วนนี้ใช้กำหนดพฤติกรรมเพิ่มเติมของ FTP Server กำหนดช่วงพอร์ตสำหรับ Passive บังคับใช้ IP เดียวกันเสมอ 
# ช่วยให้การรับส่งไฟล์เสถียร โดยเฉพาะเมื่อรันผ่าน Docker
      ADDED_FLAGS: "--passiveportrange 30000:30009 --forcepassiveip 127.0.0.1"

# กลุ่มที่ 8: การผูกโฟลเดอร์เพื่อเก็บไฟล์ถาวร
# *---* ส่วนนี้คือการเชื่อมโฟลเดอร์ในเครื่องกับใน container เพื่อให้ไฟล์ไม่หายเมื่อปิด Docker *---*
    volumes:

      - ./server_files:/home/ftpusers
      # map โฟลเดอร์ server_files บนเครื่อง host
      # ไปยัง /home/ftpusers ภายใน container
      # เพื่อให้ไฟล์ FTP ไม่หายเมื่อ container ถูก restart

# กลุ่มที่ 9: การตั้งค่าให้ระบบเสถียร
# *---* ถ้า FTP Server หยุดทำงานจากสาเหตุใดก็ตาม Docker จะสั่งเปิดใหม่ให้อัตโนมัติ *---*
    restart: always