version: "3.8"

services:

  web:
    build: .
    container_name: web-app
    ports:
      - "8000:8000"
    depends_on:
      - ftp

  ftp:
    image: stilliard/pure-ftpd
    container_name: ftp-server

    ports:
      - "21:21"
      - "30000-30009:30000-30009"

    environment:
      PUBLICHOST: "ftp"
      FTP_USER_NAME: YJ
      FTP_USER_PASS: 1234
      FTP_USER_HOME: /home/ftpusers/ftpuser1
      ADDED_FLAGS: "--passiveportrange 30000:30009 --forcepassiveip ftp"

    volumes:
      - ./server_files:/home/ftpusers/ftpuser1

    restart: always